# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9f6c35fe3ea3fcba33c9b3b649c2527dffb3ef7dc7f8d40cda6cdf7525095c52b33534805022d559515cf8cf1396a69c3840f6e08992af9e715f6b5e68cb62f

test:
  secret_key_base: 0ca2a0739b241f31feaefb2d8149eb28c891ca2fd101ae714626e5e86ffae7690af4b6aaf0989f561f3c799b9ea7789295a7105f54a1722c38d17c7189580c0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
